version: "3"

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: isucon5q
      MYSQL_DATABASE: isucon5q  # Inherit from ISUCON5_DB_NAME
    ports:
      - "63306:3306"
    volumes:
      - ./data:/var/lib/mysql

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile-golang
    restart: always
    links:
      - db
    external_links:
      - db:db
    environment:
      - ISUCON5_DB_PASSWORD=isucon5q
      - ISUCON5_DB_HOST=db
    ports:
      - "8080:8080"
